dist: trusty
sudo: required
language: go

go:
  - 1.8.x
  - 1.9.x
  - master

go_import_path: github.com/f1yegor/clickhouse_exporter

services:
  - docker

before_script:
  - docker --version
  - docker-compose --version
  - docker-compose -f docker-compose.yml up -d

script:
  - make init
  - make cover

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
